server:
  port: 18080
  servlet:
    context-path: /java-websocket

websocket:
  url:
    app-url: ws://127.0.0.1:16010
    user-url: ws://127.0.0.1:16020
  port:
    app-prot: 16010
    user-prot: 16020